# Generated by Django 3.2.8 on 2021-11-16 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='color',
            field=models.CharField(default='#9D1ACE', editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='notes',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='events.notes'),
        ),
    ]
