# Generated by Django 3.2.8 on 2021-11-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='color',
            field=models.CharField(default=['#2c60c9'], max_length=30),
        ),
    ]
