# Generated by Django 3.2.8 on 2021-10-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_appointments_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='color',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
    ]
