# Generated by Django 3.2.8 on 2021-11-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20211116_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='color',
            field=models.CharField(default='#492385', editable=False, max_length=30),
        ),
    ]
