# Generated by Django 3.2.8 on 2021-11-16 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0006_alter_appointments_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='color',
            field=models.CharField(default='#DEFB42', editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='user',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notes',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='events.appointments'),
            preserve_default=False,
        ),
    ]
